name: tfm-joint-clustering
channels:
  - conda-forge
  - gurobi
dependencies:
  - python=3.11
  - numpy=1.26.4
  - pandas=2.2.3
  - scipy=1.13.1
  - scikit-learn=1.4.2
  - matplotlib=3.8.4
  - pyyaml=6.0.2
  - pytest=8.3.5
  - pip
  - pip:
      - scikit-learn-extra==0.3.0
      - ucimlrepo==0.0.7
      - "gurobipy>=11,<14"
